'use strict';
/* TASK 4 -- minimal motif basis: try to prove or destroy it.
 *
 * Candidate: for one unresolved role X in any finite uniform macro occurrence
 * mask, the complete reduced X-support skeleton is generated by
 *   (1) one-copy local motifs,
 *   (2) two-OUTER-X midpoint-routing motifs (v0.2 section 5, gap d >= 2),
 *   (3) three-distinct-X curvature motifs C_{-1}, C_0, C_{+1} over Curv(B).
 *
 * We test COMPLETENESS in the strongest (most generous) form: each family is
 * given its full closed-form content with ambient restrictions RELAXED. Any
 * direct window signature outside that generous union is a hard counterexample
 * that no tightening of the families can repair.
 */
const G = require('./geom_core.js');
const out = {};

/* ---------- generous closed forms -------------------------------------- */
function oneCopyGen(L, kmin) {
  const S = new Set();
  for (let i = 1; i < L; i++) { S.add('1*x' + i); S.add('-2*x' + i); }
  for (let i = 1; i < L; i++) for (let j = i + kmin; j < L; j++) {
    S.add('1*x' + i + '+-2*x' + j);              // cuts q=0,1 in one copy
    S.add('-2*x' + i + '+1*x' + j);              // cuts q=1,2 in one copy
  }
  for (let a = 1; a < L; a++) for (let K = kmin; a + 2 * K < L; K++) {
    const acc = new Map(); G.bump(acc, a, 1); G.bump(acc, a + K, -2); G.bump(acc, a + 2 * K, 1);
    const s = G.fmt(acc); if (s !== '') S.add(s);
  }
  return S;
}
/* two-outer-X routing, generous: any x_i+x_j and 2*x_i, plus the curvature
   families that a d>=2 pair with an X centre can activate */
function outerPairGen(L, B) {
  const S = new Set();
  const b = [...B].sort((p, q) => p - q);
  let anyPair = false, evenXcentre = false, oddXcentre = false;
  for (let p = 0; p < b.length; p++) for (let q = p + 1; q < b.length; q++) {
    const d = b[q] - b[p]; if (d < 2) continue; anyPair = true;
    if (d % 2 === 0) { if (B.includes((b[p] + b[q]) / 2)) evenXcentre = true; }
    else { const ml = Math.floor((b[p] + b[q]) / 2);
           if (B.includes(ml) || B.includes(ml + 1)) oddXcentre = true; }
  }
  if (anyPair) {
    for (let i = 1; i < L; i++) S.add('2*x' + i);
    for (let i = 1; i < L; i++) for (let j = i + 1; j < L; j++) S.add('1*x' + i + '+1*x' + j);
  }
  if (evenXcentre) for (const s of G.Cfam(L, 0)) S.add(s);
  if (oddXcentre) { for (const s of G.Cfam(L, 1)) S.add(s); for (const s of G.Cfam(L, -1)) S.add(s); }
  return S;
}
function curvGen(L, B) {
  let S = new Set();
  for (const d of G.curvSet(B)) S = G.unionSet(S, G.Cfam(L, d));
  return S;
}
function basisPredict(L, B, kmin) {
  return G.unionSet(oneCopyGen(L, kmin), outerPairGen(L, B), curvGen(L, B));
}

/* ---------- A. COMPLETENESS: hunt the smallest counterexample ----------- */
(function () {
  const found = [];
  let cases = 0;
  outer:
  for (let L = 3; L <= 14; L++) {
    for (let N = 2; N <= 7; N++) {
      for (let m = 1; m < (1 << N); m++) {
        const B = []; for (let bb = 0; bb < N; bb++) if (m & (1 << bb)) B.push(bb);
        const direct = G.directScan(L, N, B, 2, false).set;
        const pred = basisPredict(L, B, 2);
        cases++;
        const miss = G.diffSet(direct, pred); miss.delete('');
        if (miss.size) found.push({ L, N, nX: B.length, B, missing: [...miss].sort().slice(0, 6), missingCount: miss.size });
      }
    }
  }
  // minimal by (L, N, |B|) lexicographically, then by mask
  found.sort((a, b) => a.L - b.L || a.N - b.N || a.nX - b.nX || a.missingCount - b.missingCount);
  out.A_completeness = { casesTested: cases, masksWithUncoveredSignatures: found.length,
    smallest: found.slice(0, 6) };
  console.log('A COMPLETENESS: ' + found.length + ' of ' + cases + ' masks have signatures outside the generous basis union');
  if (found.length) console.log('   smallest: ' + JSON.stringify(found[0]));
})();

/* ---------- A2. which reduced SHAPES escape the basis? ------------------ */
(function () {
  const shapes = new Map();
  for (let L = 4; L <= 12; L++) for (let N = 2; N <= 6; N++)
    for (let m = 1; m < (1 << N); m++) {
      const B = []; for (let bb = 0; bb < N; bb++) if (m & (1 << bb)) B.push(bb);
      const direct = G.directScan(L, N, B, 2, false).set;
      const pred = basisPredict(L, B, 2);
      for (const s of G.diffSet(direct, pred)) {
        if (s === '') continue;
        const sh = G.shapeOf(s);
        if (!shapes.has(sh)) shapes.set(sh, { count: 0, example: null, exampleMask: null });
        const e = shapes.get(sh); e.count++;
        if (!e.example) { e.example = s; e.exampleMask = { L, N, B }; }
      }
    }
  out.A2_escaping_shapes = [...shapes.entries()].map(([sh, v]) => ({ shape: sh, occurrences: v.count, example: v.example, mask: v.exampleMask }));
  console.log('A2 escaping reduced shapes: ' + JSON.stringify(out.A2_escaping_shapes.map(r => r.shape)));
})();

/* ---------- A3. minimal certified counterexample, fully frozen ---------- */
(function () {
  // rescan tiny masks and freeze the exact first witness window
  let best = null;
  for (let L = 3; L <= 10 && !best; L++)
    for (let N = 2; N <= 5 && !best; N++)
      for (let m = 1; m < (1 << N) && !best; m++) {
        const B = []; for (let bb = 0; bb < N; bb++) if (m & (1 << bb)) B.push(bb);
        const r = G.directScan(L, N, B, 2, true);
        const pred = basisPredict(L, B, 2);
        for (const w of r.windows) {
          if (w.sig === '' || pred.has(w.sig)) continue;
          best = { L, N, blocks: N, X_positions: B, nX: B.length, s: w.s, K: w.K, signature: w.sig,
                   contributingCuts: w.qpat, distinctXcopies: w.copies,
                   cuts: [0, 1, 2].map(q => { const t = w.s + q * w.K; return { q, t, b: Math.floor(t / L), i: t - Math.floor(t / L) * L }; }),
                   inOneCopyGen: oneCopyGen(L, 2).has(w.sig),
                   inOuterPairGen: outerPairGen(L, B).has(w.sig),
                   inCurvGen: curvGen(L, B).has(w.sig),
                   CurvB: [...G.curvSet(B)] };
          break;
        }
      }
  out.A3_frozen_counterexample = best;
  console.log('A3 frozen minimal counterexample: ' + JSON.stringify(best));
})();

/* ---------- B. REDUNDANCY ---------------------------------------------- */
(function () {
  const L = 10;
  const one = oneCopyGen(L, 2), c0 = G.Cfam(L, 0), cp = G.Cfam(L, 1), cm = G.Cfam(L, -1), M = G.midpointFamily(L);
  const inter = (A, Bs) => { let n = 0; for (const v of A) if (Bs.has(v)) n++; return n; };
  out.B_redundancy = {
    L,
    sizes: { oneCopy: one.size, C0: c0.size, Cplus: cp.size, Cminus: cm.size, midpoint: M.size },
    oneCopy_cap_C0: inter(one, c0),
    oneCopy_cap_Cplus: inter(one, cp),
    oneCopy_cap_Cminus: inter(one, cm),
    oneCopy_cap_midpoint: inter(one, M),
    midpoint_cap_C0: inter(M, c0), midpoint_cap_Cplus: inter(M, cp), midpoint_cap_Cminus: inter(M, cm),
    note: 'oneCopy 3-cut AP motifs are a proper subset of C0 (same delta=0 law, K-bounded)'
  };
  console.log('B REDUNDANCY: ' + JSON.stringify(out.B_redundancy));
})();

/* ---------- C. MINIMALITY: does each class carry a unique signature? ---- */
(function () {
  const res = {};
  const L = 8;
  // one-copy uniqueness: a mask with a single X block
  {
    const B = [0], N = 4;
    const direct = G.directScan(L, N, B, 2, false).set;
    const without = G.unionSet(outerPairGen(L, B), curvGen(L, B));
    const lost = G.diffSet(direct, without); lost.delete('');
    res.oneCopy = { mask: { L, N, B }, skeleton: direct.size, lostIfRemoved: lost.size, sample: [...lost].slice(0, 4) };
  }
  // outer-pair uniqueness: two X blocks at even gap with assigned centre
  {
    const B = [0, 2], N = 4;
    const direct = G.directScan(L, N, B, 2, false).set;
    const without = G.unionSet(oneCopyGen(L, 2), curvGen(L, B));
    const lost = G.diffSet(direct, without); lost.delete('');
    res.outerPair = { mask: { L, N, B }, skeleton: direct.size, lostIfRemoved: lost.size, sample: [...lost].slice(0, 4) };
  }
  // curvature uniqueness: three X blocks in AP (delta=0) and irregular (delta=+1)
  for (const [tag, B, N] of [['AP_delta0', [0, 2, 4], 6], ['irregular_delta1', [0, 2, 5], 6]]) {
    const direct = G.directScan(L, N, B, 2, false).set;
    const without = G.unionSet(oneCopyGen(L, 2), outerPairGen(L, B));
    const lost = G.diffSet(direct, without); lost.delete('');
    res[tag] = { mask: { L, N, B }, skeleton: direct.size, lostIfRemoved: lost.size, sample: [...lost].slice(0, 4) };
  }
  out.C_minimality = res;
  console.log('C MINIMALITY: ' + JSON.stringify(res));
})();

/* ---------- D. canonical reduced-shape catalogue ------------------------ */
(function () {
  const cat = new Map();
  for (let L = 4; L <= 11; L++) for (let N = 2; N <= 6; N++)
    for (let m = 1; m < (1 << N); m++) {
      const B = []; for (let bb = 0; bb < N; bb++) if (m & (1 << bb)) B.push(bb);
      const r = G.directScan(L, N, B, 2, true);
      for (const w of r.windows) {
        const sh = G.shapeOf(w.sig);
        if (!cat.has(sh)) cat.set(sh, { count: 0, example: w.sig, mask: { L, N, B }, qpat: w.qpat, copies: w.copies });
        cat.get(sh).count++;
      }
    }
  out.D_shape_catalogue = [...cat.entries()].sort((a, b) => b[1].count - a[1].count)
    .map(([sh, v]) => ({ shape: sh, windows: v.count, example: v.example, firstSeen: v.mask, cuts: v.qpat, copies: v.copies }));
  console.log('D CATALOGUE (' + out.D_shape_catalogue.length + ' reduced shapes): ' +
    JSON.stringify(out.D_shape_catalogue.map(r => r.shape)));
})();

require('fs').writeFileSync(__dirname + '/../motif_basis_results.json', JSON.stringify(out, null, 1));
