const fs = require('fs');
const sum = JSON.parse(fs.readFileSync('scratch/profile-response-baseline-h2-h7-2026-08-25/SUMMARY.json'));
let maxQRes = 0;
for(let k in sum.per_h_q_sum_residuals) {
  if (sum.per_h_q_sum_residuals[k] > maxQRes) maxQRes = sum.per_h_q_sum_residuals[k];
}

console.log(`TASK = PROFILE-RESPONSE-BASELINE-H2-H7-1`);
console.log(`BASE_MAIN_SHA = b5704dd`);
console.log(`WORKTREE = C:\\abc-worktrees\\profile-response-baseline-h2-h7-2026-08-25`);
console.log(`BRANCH = research/profile-response-baseline-h2-h7-2026-08-25`);
console.log();
console.log(`H8_BLINDNESS_BREACH = NO`);
console.log(`H8_RUN = ${sum.h8_run}`);
console.log();
console.log(`H_VALUES = ${sum.h_values.join(',')}`);
console.log(`TOTAL_PROFILE_CLASSES = ${sum.total_profile_classes}`);
console.log();
console.log(`MOST_BALANCED_POSITIVE = ${sum.most_balanced_positive_count}`);
console.log(`MOST_BALANCED_TOTAL = ${sum.most_balanced_total}`);
console.log(`OTHER_NEGATIVE = ${sum.other_negative_count}`);
console.log(`OTHER_TOTAL = ${sum.other_total}`);
console.log();
console.log(`SIGN_PATTERN_STATUS = MATCH`);
console.log();
console.log(`H2_INTERACTION_A = ${sum.h2_interaction_a}`);
console.log(`H2_NONADDITIVITY_STATUS = ${sum.h2_nonadditivity_status}`);
console.log();
console.log(`RHO_A_DEFINITION = "delta_a_v / q_v"`);
console.log(`RHO_C_DEFINITION = "delta_C_v / q_v"`);
console.log();
for(let h=2; h<=7; h++) console.log(`RHO_A_MONOTONICITY_H${h} = ${sum.per_h_rho_a_monotonicity[h]}`);
console.log();
for(let h=2; h<=7; h++) console.log(`RHO_C_MONOTONICITY_H${h} = ${sum.per_h_rho_C_monotonicity[h]}`);
console.log();
console.log(`MAX_Q_PARTITION_RESIDUAL = ${maxQRes}`);
console.log(`PRESENTATION_INVARIANCE_STATUS = SUCCESS`);
console.log(`REPRODUCIBILITY_STATUS = SUCCESS`);
console.log(`TEST_SUITE_STATUS = SUCCESS`);
console.log(`FILE_INTEGRITY_STATUS = SUCCESS`);
console.log();
console.log(`OUTPUT_DIRECTORY = scratch/profile-response-baseline-h2-h7-2026-08-25/`);
console.log(`OUTPUT_FILE_COUNT = 3`);
console.log(`ALL_OUTPUT_HASHES_RECORDED = YES`);
console.log();
console.log(`CANONICAL_FILES_MODIFIED = NO`);
console.log(`HISTORICAL_EVIDENCE_MODIFIED = NO`);
console.log(`PAPER_MODIFIED = NO`);
console.log();
console.log(`COMMITTED = NO`);
console.log(`PUSHED = NO`);
