#!/usr/bin/env python3
"""Decisive null control for the Paper-6 space-time observability spectrum.

Claim under test: nu_m = ceil(d / g_m) for m = 1,2,3 is a meaningful property of
recency-gauged Parikh-profile measurements.

Competing explanation: V_cnt is a CYCLIC Q-module (it is the cyclic subspace
generated by 1, and its minimal polynomial has degree d = dim V_cnt).  For a
cyclic operator, the dual V* is a cyclic k[x]-module of dimension d, the rows of
O_t are the classes x^j c_i, and for GENERIC covectors c_1..c_g the span of
{x^j c_i : j<t, i<=g} has dimension min(tg, d).  Hence nu = ceil(d/g) is the
generic value and conformance is the null hypothesis, not the finding.

Test: replace the profile partition by a RANDOM partition of the same raw
histories with the SAME number of families and the SAME family-size
distribution, and recompute.  If random partitions also attain ceil(d/g), the
conformance carries no Abelian information; only a deviation does.

Independent of the shipped replay: own aggregation, own Krylov build, own
mod-p rank (no C++ helper).
"""
import json
import sys
from pathlib import Path

import numpy as np
from scipy.sparse import coo_matrix, csr_matrix

R = Path(sys.argv[1])
PRIME = 65521
D = 1179
SEEDS = (11, 22, 33)

states = [x.decode("ascii").rstrip("\x00")
          for x in np.load(R / "P6_Q2_RAW_STATES_S21.npy")]
classes = np.load(R / "P6_Q2_RAW_TO_EQUITABLE_CLASS_U16.npy").astype(np.int64)
J = json.loads((R / "P6_Q2_EQUITABLE_QUOTIENT_SPARSE_v0.1_2026-08-30.json").read_text())
rr, cc, dd = [], [], []
for i, row in enumerate(J["rows"]):
    for j, w in row:
        rr.append(i); cc.append(j); dd.append(w)
N = 2691
Q = csr_matrix((np.array(dd, dtype=np.int64), (rr, cc)), shape=(N, N))


def recency_map(s):
    order = []
    for c in reversed(s):
        if c not in order:
            order.append(c)
        if len(order) == 3:
            break
    for c in "abc":
        if c not in order:
            order.append(c)
    return {order[i]: "abc"[i] for i in range(3)}


def parikh(w):
    return (w.count("a"), w.count("b"), w.count("c"))


def label(s, m):
    mp = recency_map(s)
    t = "".join(mp[c] for c in s)
    a = len(t) % 4
    blocks = [t[i:i + 4] for i in range(a, len(t), 4) if i + 4 <= len(t)]
    ps = [parikh(b) for b in blocks[-m:]]
    while len(ps) < m:
        ps.insert(0, None)
    return tuple(ps)


def gids_from_labels(labels):
    mp, gid = {}, np.empty(len(labels), dtype=np.int64)
    for i, x in enumerate(labels):
        if x not in mp:
            mp[x] = len(mp)
        gid[i] = mp[x]
    return gid, len(mp)


def aggregation_from_gids(gid, g):
    G = coo_matrix((np.ones(len(gid), dtype=np.int64), (gid, classes)),
                   shape=(g, N)).tocsr()
    G.sum_duplicates()
    return G


def rank_mod(X, p):
    A = (np.asarray(X, dtype=np.int64) % p).copy()
    m, n = A.shape
    r = 0
    for c in range(n):
        if r >= m:
            break
        nz = np.flatnonzero(A[r:, c])
        if nz.size == 0:
            continue
        k = r + int(nz[0])
        if k != r:
            A[[r, k]] = A[[k, r]]
        A[r, c:] = (A[r, c:] * pow(int(A[r, c]), p - 2, p)) % p
        col = A[r + 1:, c]
        nzf = np.flatnonzero(col)
        if nzf.size:
            ids = r + 1 + nzf
            A[ids, c:] = (A[ids, c:] - col[nzf, None] * A[r, c:][None, :]) % p
        r += 1
    return r


MAX_T = 197
print("building Krylov basis ...", flush=True)
V = np.empty((N, D + MAX_T - 1), dtype=np.int64)
v = np.ones(N, dtype=np.int64)
for h in range(V.shape[1]):
    V[:, h] = v % PRIME
    v = np.asarray(Q.dot(v)).ravel() % PRIME
print("done", flush=True)


def stack_rank(G, t):
    S = np.vstack([G.dot(V[:, j:j + D]) % PRIME for j in range(t)])
    return rank_mod(S, PRIME)


TESTS = {1: 197, 2: 24, 3: 4, 4: 1}   # m -> ceil(d/g_m)  (m=4 bound is 1)
results = {}

print(f"\n{'m':>2} {'g':>5} {'ceil(d/g)':>9} {'real rank@t':>12} "
      f"{'random ranks@t (3 seeds)':>32}")
for m, t in TESTS.items():
    labels = [label(s, m) for s in states]
    gid, g = gids_from_labels(labels)
    G = aggregation_from_gids(gid, g)
    real = stack_rank(G, t)

    sizes = np.bincount(gid, minlength=g)
    rnd = []
    for seed in SEEDS:
        rng = np.random.default_rng(seed)
        perm = rng.permutation(len(states))
        rgid = np.empty(len(states), dtype=np.int64)
        pos = 0
        for gi, sz in enumerate(sizes):
            rgid[perm[pos:pos + sz]] = gi
            pos += sz
        assert pos == len(states)
        rnd.append(stack_rank(aggregation_from_gids(rgid, g), t))

    results[m] = {"g": int(g), "bound": t, "real": int(real),
                  "random": [int(x) for x in rnd],
                  "size_min": int(sizes.min()), "size_max": int(sizes.max())}
    print(f"{m:>2} {g:>5} {t:>9} {real:>12} {str(rnd):>32}", flush=True)

print(f"\ntarget dimension d = {D}")
print("interpretation: if the random column matches the real column, the")
print("row-count optimality carries no Abelian information at that depth.")
(R / "AUDIT_GENERICITY_NULL_RESULTS.json").write_text(json.dumps(results, indent=2))
