const { G85 } = require('../src/morphisms.js');
const boundaries = ['cbd', 'bdb', 'ad', 'bad', 'cad', 'dbd', 'adb'];
const blocks = { 'a': G85['a'], 'b': G85['b'], 'c': G85['c'], 'd': G85['d'] };

function checkBackward(B) {
    let exactSuffix = false;
    let crossBoundary = false;
    let predecessors = [];
    
    // Check exact suffix
    for (let c in blocks) {
        if (blocks[c].endsWith(B)) {
            exactSuffix = true;
            predecessors.push(c);
        }
    }
    
    // Check cross boundary when followed by X (which starts with 'a')
    // Wait, the block boundary is exactly where B ends and X begins. 
    // This means B must be the end of the previous block, because X starts a new block!
    // So B MUST be a suffix. 
    // What if B is longer than 85? No, they are length 2 or 3.
    // What if B is NOT a suffix of a full block, but we want B to be the suffix of SOME left-context generated by G85?
    // Any left-context generated by G85 that ends exactly before X MUST end with a complete block.
    // So the last block must end with B.
    
    if (exactSuffix) {
        return `MORPHIC BACKWARD (${predecessors.join(',')})`;
    } else {
        return "NO G85 BACKWARD";
    }
}

for (let b of boundaries) {
    console.log(`${b}: ${checkBackward(b)}`);
}

// Let's also verify their last 3 characters of blocks just to be sure:
for (let c in blocks) {
    console.log(`Block ${c} ends with: ${blocks[c].slice(-5)}`);
}
