const { G85 } = require('../src/morphisms.js');
const alphabet = ['a', 'b', 'c', 'd'];

function getParikh(str) {
    let p = [0,0,0,0];
    for(let c of str) p[alphabet.indexOf(c)]++;
    return p;
}

let M85 = [
    getParikh(G85['a']),
    getParikh(G85['b']),
    getParikh(G85['c']),
    getParikh(G85['d'])
];
// M85[i] is the Parikh vector of G85(alphabet[i])
// To solve M85 * x = y, since columns of M85 are P(g(a)), P(g(b))...
// Actually, M85 * x = sum x_i P(g(alpha_i))
// We want to find x given y.
// Let's just do a brute force search for x since x components are small!
// The discrepancy y is bounded. x must be an integer vector.
// Since M85 is invertible and determinant is large, x must be small.
// Let's search x in [-10, 10]^4

function solve(y) {
    for(let x0 = -10; x0 <= 10; x0++) {
    for(let x1 = -10; x1 <= 10; x1++) {
    for(let x2 = -10; x2 <= 10; x2++) {
    for(let x3 = -10; x3 <= 10; x3++) {
        let sum0 = x0*M85[0][0] + x1*M85[1][0] + x2*M85[2][0] + x3*M85[3][0];
        if (sum0 !== y[0]) continue;
        let sum1 = x0*M85[0][1] + x1*M85[1][1] + x2*M85[2][1] + x3*M85[3][1];
        if (sum1 !== y[1]) continue;
        let sum2 = x0*M85[0][2] + x1*M85[1][2] + x2*M85[2][2] + x3*M85[3][2];
        if (sum2 !== y[2]) continue;
        let sum3 = x0*M85[0][3] + x1*M85[1][3] + x2*M85[2][3] + x3*M85[3][3];
        if (sum3 !== y[3]) continue;
        return [x0, x1, x2, x3];
    }}}}
    return null;
}

// We want to find the closure of Q.
// Q starts with [-2,1,0,0].
// But wait! Is [-2,1,0,0] the ONLY state generated by a crossing square?
// Let's first generate all crossing square residual states for `ad | g85(V)`.
let crossing_states = new Set();
// U starts in `ad`, so U starts at index 0 or 1.
let B = "ad";
// U length K, V length K.
// U = B[i:] + g85(V)[0 .. K - |B[i:]|]
// V = g85(V)[K - |B[i:]| .. 2K - |B[i:]|]
// Let's just represent this as:
// The square boundary is at index K in B + g85(V).
// U is before K, V is after K.
// We align the boundary to g85(c).
// Let the g85 blocks of V be c_0, c_1, ...
// The square boundary is inside c_k at offset o.
// So U takes B[i:] and then full blocks, then prefix of c_k.
// V takes suffix of c_k, then full blocks, then prefix of c_m at offset o2.
// Actually, this is exactly what we did in P7_16!
// Let's rewrite the exact generator for P7_16 residual states.

let Q = [];
let Q_set = new Set();

function addState(q, source) {
    let key = q.join(',');
    if (!Q_set.has(key)) {
        Q_set.add(key);
        Q.push(q);
        console.log(`Added state: [${key}] from ${source}`);
    }
}

// 1. Squares crossing `ad | g85(V)`
for (let i = 0; i < B.length; i++) {
    // U starts at i in B. So U takes B[i:]
    let p_U_start = getParikh(B.slice(i));
    
    // The middle boundary (between U and V) is in some block c_mid at offset o_mid
    for (let c_mid of alphabet) {
        let g_mid = G85[c_mid];
        for (let o_mid = 0; o_mid < 85; o_mid++) {
            // U ends at o_mid in c_mid. So U takes g_mid[:o_mid]
            let p_U_end = getParikh(g_mid.slice(0, o_mid));
            
            // V starts at o_mid in c_mid. So V takes g_mid[o_mid:]
            let p_V_start = getParikh(g_mid.slice(o_mid));
            
            // The end of V is in some block c_end at offset o_end
            for (let c_end of alphabet) {
                let g_end = G85[c_end];
                for (let o_end = 0; o_end < 85; o_end++) {
                    // V ends at o_end in c_end. So V takes g_end[:o_end]
                    let p_V_end = getParikh(g_end.slice(0, o_end));
                    
                    // U and V lengths must be equal.
                    // |U| = |B[i:]| + 85 * |W_U| + o_mid
                    // |V| = (85 - o_mid) + 85 * |W_V| + o_end
                    let len_diff = (B.length - i) + o_mid - (85 - o_mid) - o_end;
                    if (len_diff % 85 !== 0) continue;
                    let num_blocks_diff = -len_diff / 85; // |W_U| - |W_V|
                    
                    // We want P(U) = P(V)
                    // P(U) = p_U_start + p_U_end + M85 * W_U
                    // P(V) = p_V_start + p_V_end + M85 * W_V
                    // M85 * (W_U - W_V) = p_V_start + p_V_end - p_U_start - p_U_end
                    let y = [0,0,0,0];
                    for(let k=0; k<4; k++) y[k] = p_V_start[k] + p_V_end[k] - p_U_start[k] - p_U_end[k];
                    
                    let dW = solve(y);
                    if (dW !== null) {
                        // verify length
                        let sum_dW = dW[0]+dW[1]+dW[2]+dW[3];
                        if (sum_dW === num_blocks_diff) {
                            // This means dW is a valid discrepancy vector for full blocks in V!
                            // W_U and W_V are adjacent?
                            // U spans from B[i:] to c_mid. So W_U is the blocks *before* c_mid.
                            // V spans from c_mid to c_end. So W_V is the blocks *between* c_mid and c_end.
                            // So in V, we have: W_U (empty because it's at start of V), then c_mid, then W_V, then c_end.
                            // Wait, W_U is the blocks in g85(V). So W_U corresponds to a prefix of V!
                            // V = W_U * c_mid * W_V * c_end ...
                            // We need to express this as a near-square in V.
                            // The left part in V is `W_U`. The right part is `W_V`.
                            // What is the Parikh difference? P(W_U) - P(W_V) = dW.
                            // Wait, `W_U` and `W_V` are NOT adjacent in V. They are separated by `c_mid`.
                            // Let's define the near-square precisely:
                            // We want a state that describes: "V has a factor W_U, then c_mid, then W_V, such that P(W_U) - P(W_V) = dW".
                            // Actually, let's just record the tuple: (dW, c_mid).
                            // A near-square is parameterized by: dW (vector), and the boundary letter(s).
                            // Let's just collect all unique dW!
                            addState(dW, "Crossing ad");
                        }
                    }
                }
            }
        }
    }
}
